"""empty message

Revision ID: 55a877bcdc51
Revises: 
Create Date: 2023-08-04 15:15:35.049842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a877bcdc51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_name', sa.String(length=255), nullable=False),
    sa.Column('admin_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('contact',
    sa.Column('cont_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cont_name', sa.String(length=255), nullable=False),
    sa.Column('cont_email', sa.String(length=255), nullable=False),
    sa.Column('cont_phone', sa.String(length=255), nullable=False),
    sa.Column('cont_msg', sa.Text(), nullable=False),
    sa.Column('cont_reg_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cont_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    op.drop_table('admin')
    # ### end Alembic commands ###
